import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

try:
    from PIL import Image
except ImportError:
    print("Installing Pillow...")
    install('Pillow')
    from PIL import Image

try:
    # Open the image generated by fetch_mermaid_png.py
    img = Image.open('timeline_architecture.png').convert("RGBA")
    
    # Create a new solid pure black image to act as the true background
    bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
    
    # Composite the images using the original image as a source and its alpha channel as a mask
    final_img = Image.alpha_composite(bg, img)
    final_img = final_img.convert("RGB") # Remove alpha channel before saving as final PNG, guaranteeing no transparency rendering bugs
    
    final_img.save('timeline_architecture.png')
    print("Successfully added a permanent #000000 black background to timeline_architecture.png")
except Exception as e:
    print(f"Error processing image: {e}")
